pool:
  vmImage: 'ubuntu-16.04'
trigger:
  - master
steps:
  - task: CopyFiles@2
    displayName: 'Copy Files to: $(build.artifactstagingdirectory)/manager'
    inputs:
      SourceFolder: $(build.artifactstagingdirectory)
      Contents: '*.json'
      TargetFolder: '$(build.artifactstagingdirectory)'
  - task: ArchiveFiles@2
    displayName: 'Archive $(Build.SourcesDirectory)'
    inputs:
      rootFolderOrFile: '$(Build.SourcesDirectory)'
      includeRootFolder: false
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: drop'